Run tests on ubuntu 22.04 (gstreamer 1.20 required) (#304)
* run tests on ubuntu 22.04 (gstreamer 1.20 required)

* fix installs

* install gstreamer tools

* remove libunwind-dev

* remove libunwind-14-dev

* install gstreamer dependencies

* fix gstreamer deps in ci/deploy pipelines

* upgrade libglib-2.0

* fix ubuntu version

* uninstall libunwind-14-dev

* upgrade libglib-2.0 in cross images

* upgrade ubuntu version

* upgrade cross images to 22.04

* hack cross build scripts for 22.04

* Disable armv7 (SIMD not supported)

error[E0425]: cannot find function `write_str_simd` in this scope
   --> /cargo/registry/src/github.com-1ecc6299db9ec823/value-trait-0.4.0/src/generator.rs:162:19
    |
162 |             stry!(write_str_simd(self.get_writer(), &mut string,));
    |                   ^^^^^^^^^^^^^^ not found in this scope

For more information about this error, try `rustc --explain E0425`.
error: could not compile `value-trait` due to previous error

* install nnstreamer deps in cross images

* fix cross workflow errrs

* move test model into tests/fixtures

* fix test fixture

* ignore  test_dataframe_filesink